### ISSUE TITLE
Using heapallindexed to verify backup

### ISSUE THREAD

**Issue by x4m** [petergeoghegan/amcheck#10]
Hi, Peter!

I'm working on backup tool WAL-G. One of its neat features is LSN-based delta-backups.
I'm looking for the way for effective backup verification. For normal backup pg_dumpall>/dev/null is sufficient, but in delta backups I'm afraid of losing pages, having stale pages etc.

Can heapallindexed be useful for backup verification for delta-backups?
I can make pg_dump everything that has no indexes and amcheck-heapallindexed every table that has at least one index. This should be sufficient to say that we have the bijection between all alive index tuples and heap tuples?

**Comment by petergeoghegan** [comment]
Hi,

I know the maintainers of WAL-G, fwiw.

I think that that would be an effective strategy. amcheck will generally be a lot more effective at detecting corruption than pg_dump (there are probably cases where pg_dump can do better, but overall amcheck will look at a lot more). The bijection between heap tuples and index tuples is not a simple one with concurrent writes, because we need to use knowledge of heap tuple lifetime to avoid false positive bugs (from race conditions).

It would probably be worth your while to test each index in its own transaction, at least for large indexes (I'm assuming you're using bt_index_check(), and not bt_index_parent_check(), where none of this matters). That way, the TransactionXmin value would not become too stale, which would reduce the effectiveness of the verification. That's a risk with a "one large query" approach, that you should try to avoid. When we ran amcheck on Heroku, we ended up running each index check in its own transaction.

**Comment by x4m** [comment]
Thanks for your thoughts, Peter!

I'll put in some details:
1. In backup verification, I really do not care about index corruption. Not just do not care, but even prefer to ignore it, let database with corrupted index live it's life inside the database, as long as I have means to bring back users database with PITR (even if I will bring corrupted index). The thing I care is heap: indexes are just a hacky way to check that nothing is lost in heap.
2. There is neither writes not reads during backup verification. The whole cluster is restored for only one purpose: check that backup is valid, then drop freshly restored cluster. Verification lives on separate containers that are bothered only by checking that everything is OK with backups.

**Comment by petergeoghegan** [comment]
FWIW, I don't think that it's necessary to restore a backup in own container in order to perform verification -- impact on production should hopefully be fairly limited. But, if you do have a dedicated container that runs through recovery, then bt_index_check() may still be better than bt_index_parent_check() -- the latter function does more verification of the index structure, which you've said you don't care about. OTOH, it is useful to restore the actual backup in some ways -- it ensures that you won't fail to notice corrupt data when it's corrupt on disk but not in shared_buffers. You're testing *the backup*.

I don't think that the apparently-wasted overhead of verifying the index will be a huge problem for you. Most of the overhead of the index walking phase comes from I/O, and matching the index against the heap is the best way of verifying the backup. Sure, there should be another option to directly target heap relations, and I think that there will be in a future version, but I mostly see that as a way of lowering the overhead of heapallindexed verification. A B-Tree index is essentially a redundant copy of some of the attributes in the heap (those that are indexed), and that's an excellent thing to take advantage of during verification, even if it's a bit expensive. I still see most verification time being spent in the heap when the heapallindexed option is in use. I think I estimated this at 5x of the time of the index verification (non-heapallindexed case), but it could be even more.

Anyway, I'm glad that you're working on this problem from a backup point of view. I probably should have done more work with people that work on backups already (I did informally try to get the pgBackrest people to look into it). The functionality in amcheck will work best within a higher level tool that manages all of the low level details in a high level way, on the user's behalf. That's how the community will realize the full benefit of the tool.

I'm going to close this issue out. I'm happy to help you with this in the future, though.
